- name: Reboot devices
  hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('rpies', true) }}"
  tasks:
    - name: Reboot
      become: yes
      reboot:
        reboot_timeout: 200
      ignore_errors: yes
      ignore_unreachable: yes
