- name: Shutdown devices
  hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('rpies', true) }}"
  gather_facts: no
  tasks:
    - name: Shutdown
      become: yes
      ignore_errors: yes
      ignore_unreachable: yes
      shell: poweroff
